#include "global_ui_transition_config_table.h"

static UiStateId table[BUTTON_ID_COUNT] = {
    [BUTTON_ID_NONE] = ID_NONE,
    [BUTTON_ID_NULL] = ID_NULL,
    [BUTTON_ID_LEFT] = UI_STATE_ID_NONE,
    [BUTTON_ID_RIGHT] = UI_STATE_ID_NONE,
    [BUTTON_ID_ENTER] = UI_STATE_ID_NONE,
    [BUTTON_ID_EXIT] = UI_STATE_ID_NONE,
    [BUTTON_ID_ENCODER_A_PUSH] = UI_STATE_ID_NONE, // 엔코더 푸시 버튼의 동작은 패널마다 다르므로 이곳에서 정의하지 않음
    [BUTTON_ID_ENCODER_B_PUSH] = UI_STATE_ID_NONE,
    [BUTTON_ID_ENCODER_C_PUSH] = UI_STATE_ID_NONE,
    [BUTTON_ID_ENCODER_D_PUSH] = UI_STATE_ID_NONE,
    [BUTTON_ID_IFX_A_TOGGLE] = UI_STATE_ID_NONE,
    [BUTTON_ID_TFX_A_TOGGLE] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_1_EDIT] = UI_STATE_ID_SETTING,
    [BUTTON_ID_TRACK_1_PLAY_RECORD] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_1_STOP] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_2_EDIT] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_2_PLAY_RECORD] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_2_STOP] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_3_EDIT] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_3_PLAY_RECORD] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_3_STOP] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_4_EDIT] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_4_PLAY_RECORD] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_4_STOP] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_5_EDIT] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_5_PLAY_RECORD] = UI_STATE_ID_NONE,
    [BUTTON_ID_TRACK_5_STOP] = UI_STATE_ID_NONE,
};

UiStateId GlobalUiTransitionConfigTable_Get(ButtonId id)
{
    if (id <= BUTTON_ID_NONE || id >= BUTTON_ID_COUNT) {
        return UI_STATE_ID_NONE;
    }
    return table[id];
}
