#include "button_track_action_config_table.h"

#include "enum_map.hpp"

static constexpr EnumMap<ButtonId, TrackActionId, BUTTON_ID_COUNT>
    button_track_action_map{
        EnumEntry{BUTTON_ID_NONE, TRACK_ACTION_ID_NONE},
        EnumEntry{BUTTON_ID_NULL, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_LEFT, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_RIGHT, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_ENTER, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_EXIT, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_ENCODER_A_PUSH, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_ENCODER_B_PUSH, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_ENCODER_C_PUSH, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_ENCODER_D_PUSH, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_IFX_A_TOGGLE, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_TFX_A_TOGGLE, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_TRACK_1_EDIT, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_TRACK_1_PLAY_RECORD,
                  TRACK_ACTION_ID_ENTER_RECORD_PLAY},
        EnumEntry{BUTTON_ID_TRACK_1_STOP, TRACK_ACTION_ID_ENTER_STOP},
        EnumEntry{BUTTON_ID_TRACK_2_EDIT, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_TRACK_2_PLAY_RECORD,
                  TRACK_ACTION_ID_ENTER_RECORD_PLAY},
        EnumEntry{BUTTON_ID_TRACK_2_STOP, TRACK_ACTION_ID_ENTER_STOP},
        EnumEntry{BUTTON_ID_TRACK_3_EDIT, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_TRACK_3_PLAY_RECORD,
                  TRACK_ACTION_ID_ENTER_RECORD_PLAY},
        EnumEntry{BUTTON_ID_TRACK_3_STOP, TRACK_ACTION_ID_ENTER_STOP},
        EnumEntry{BUTTON_ID_TRACK_4_EDIT, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_TRACK_4_PLAY_RECORD,
                  TRACK_ACTION_ID_ENTER_RECORD_PLAY},
        EnumEntry{BUTTON_ID_TRACK_4_STOP, TRACK_ACTION_ID_ENTER_STOP},
        EnumEntry{BUTTON_ID_TRACK_5_EDIT, TRACK_ACTION_ID_NULL},
        EnumEntry{BUTTON_ID_TRACK_5_PLAY_RECORD,
                  TRACK_ACTION_ID_ENTER_RECORD_PLAY},
        EnumEntry{BUTTON_ID_TRACK_5_STOP, TRACK_ACTION_ID_ENTER_STOP},
    };

TrackActionId ButtonTrackActionConfigMap_Get(ButtonId id) {
  if (id <= BUTTON_ID_NONE || id >= BUTTON_ID_COUNT) {
    return TRACK_ACTION_ID_NONE;
  }
  return button_track_action_map[id];
}
