#ifndef TRACK_MEASURE_HPP
#define TRACK_MEASURE_HPP

#include <cstdint>

enum class TrackMeasure : std::uint8_t {
  SIXTEENTH,
  DOTTED_SIXTEENTH,
  QUARTER_SIXTEENTH,
  EIGHTH,
  DOTTED_EIGHTH,
  TRIPLET_EIGHTH,
  QUARTER,
  DOTTED_QUARTER,
  TRIPLET_QUARTER,
  HALF,
  DOTTED_HALF,
  TRIPLET_HALF,
  WHOLE_NOTE,
  DOUBLE_WHOLE_NOTE,
  THREE_WHOLE_NOTE,
  FOUR_WHOLE_NOTE,
};

#endif
