#ifndef BUTTON_ID_H
#define BUTTON_ID_H

#include <stdint.h>

#include "id.h"

typedef enum {
  BUTTON_ID_NONE = ID_NONE,
  BUTTON_ID_NULL = ID_NULL,
  BUTTON_ID_LEFT,
  BUTTON_ID_RIGHT,
  BUTTON_ID_ENTER,
  BUTTON_ID_EXIT,
  BUTTON_ID_ENCODER_A_PUSH,
  BUTTON_ID_ENCODER_B_PUSH,
  BUTTON_ID_ENCODER_C_PUSH,
  BUTTON_ID_ENCODER_D_PUSH,
  BUTTON_ID_IFX_A_TOGGLE,
  BUTTON_ID_TFX_A_TOGGLE,
  BUTTON_ID_TRACK_1_EDIT,
  BUTTON_ID_TRACK_1_PLAY_RECORD,
  BUTTON_ID_TRACK_1_STOP,
  BUTTON_ID_TRACK_2_EDIT,
  BUTTON_ID_TRACK_2_PLAY_RECORD,
  BUTTON_ID_TRACK_2_STOP,
  BUTTON_ID_TRACK_3_EDIT,
  BUTTON_ID_TRACK_3_PLAY_RECORD,
  BUTTON_ID_TRACK_3_STOP,
  BUTTON_ID_TRACK_4_EDIT,
  BUTTON_ID_TRACK_4_PLAY_RECORD,
  BUTTON_ID_TRACK_4_STOP,
  BUTTON_ID_TRACK_5_EDIT,
  BUTTON_ID_TRACK_5_PLAY_RECORD,
  BUTTON_ID_TRACK_5_STOP,
  BUTTON_ID_COUNT,
} ButtonId;

typedef enum { BUTTON_STATE_RELEASED = 0, BUTTON_STATE_PRESSED } ButtonState;

#endif
