#ifndef CONTROL_BUTTON_ID_H
#define CONTROL_BUTTON_ID_H

#include <stdint.h>

typedef enum {
    CONTROL_BUTTON_ID_NONE = 0,
    CONTROL_BUTTON_ID_LEFT,
    CONTROL_BUTTON_ID_RIGHT,
    CONTROL_BUTTON_ID_ENTER,
    CONTROL_BUTTON_ID_EXIT,
    CONTROL_BUTTON_ID_ENCODER_A_PUSH,
    CONTROL_BUTTON_ID_ENCODER_B_PUSH,
    CONTROL_BUTTON_ID_ENCODER_C_PUSH,
    CONTROL_BUTTON_ID_ENCODER_D_PUSH,
    CONTROL_BUTTON_ID_IFX_A_TOGGLE,
    CONTROL_BUTTON_ID_TFX_A_TOGGLE,
    CONTROL_BUTTON_ID_TRACK_1_EDIT,
    CONTROL_BUTTON_ID_TRACK_1_PLAY_RECORD,
    CONTROL_BUTTON_ID_TRACK_1_STOP,
    CONTROL_BUTTON_ID_TRACK_2_EDIT,
    CONTROL_BUTTON_ID_TRACK_2_PLAY_RECORD,
    CONTROL_BUTTON_ID_TRACK_2_STOP,
    CONTROL_BUTTON_ID_TRACK_3_EDIT,
    CONTROL_BUTTON_ID_TRACK_3_PLAY_RECORD,
    CONTROL_BUTTON_ID_TRACK_3_STOP,
    CONTROL_BUTTON_ID_TRACK_4_EDIT,
    CONTROL_BUTTON_ID_TRACK_4_PLAY_RECORD,
    CONTROL_BUTTON_ID_TRACK_4_STOP,
    CONTROL_BUTTON_ID_TRACK_5_EDIT,
    CONTROL_BUTTON_ID_TRACK_5_PLAY_RECORD,
    CONTROL_BUTTON_ID_TRACK_5_STOP,
} ControlButtonId;

typedef enum {
  CONTROL_BUTTON_STATE_RELEASED = 0,
  CONTROL_BUTTON_STATE_PRESSED
} ControlButtonState;

#endif
