#ifndef KNOB_ID_H
#define KNOB_ID_H

#include "id.h"

typedef enum {
    KNOB_ID_NONE = ID_NONE,
    KNOB_ID_NULL = ID_NULL,
    KNOB_ID_IFX,
    KNOB_ID_TFX,
    KNOB_ID_TRACK_1_VOLUME_FADER,
    KNOB_ID_TRACK_2_VOLUME_FADER,
    KNOB_ID_TRACK_3_VOLUME_FADER,
    KNOB_ID_TRACK_4_VOLUME_FADER,
    KNOB_ID_TRACK_5_VOLUME_FADER,
    KNOB_ID_COUNT,
} KnobId;

#endif
