#ifndef UI_PANEL_SLOT_INDEX_H
#define UI_PANEL_SLOT_INDEX_H

typedef enum {
    UI_PANEL_SLOT_INDEX_A = 0,
    UI_PANEL_SLOT_INDEX_B,
    UI_PANEL_SLOT_INDEX_C,
    UI_PANEL_SLOT_INDEX_D,
    UI_PANEL_SLOT_INDEX_COUNT,
} UiPanelSlotIndex;

#endif
